In [1]:
!pip install numpy

In [2]:
import numpy as np #np is a alias name of numpy module

In [3]:
np.__version__

'1.20.1'

# create a 1D array

In [4]:
#1D array means list of array
#array() inbuilt method of numpy
a=np.array([89,85,96,75,48,55,78,83])#a is numpy array object

In [5]:
print(a)

[89 85 96 75 48 55 78 83]


In [6]:
#to check the dimension of array a,use inbuilt method ndim of numpy
a.ndim

1

In [7]:
#to check type of array
a.dtype

dtype('int32')

In [8]:
#to check the datatype of a
type(a)#here nd means no.of dimension

numpy.ndarray

In [9]:
#how many element in numpy array a, use inbuilt method size
a.size

8

In [10]:
#how many rows and columns in given numpy array a,use inbuilt shape
#its return answer in tuple
a.shape

(8,)

In [11]:
#each element occupy 4bytes memory space of array a
a.itemsize

4

In [12]:
#to find the total no.of bytes occupy by array a
#use inbuilt method nbytes
a.nbytes

32

In [13]:
#to find no.of element in numpy array
#1.size inbuilt method or 2.len():inbuilt function
a.size

8

In [14]:
len(a)

8

In [15]:
#create a 1D array with int type
a=np.array([45,52,62,34.2,48],int)#with the use of (int)we can change float into int
print(a)
print('data type of a:',a.dtype)

[45 52 62 34 48]
data type of a: int32


In [16]:
#there are 2types of access data from 1D numpy array
#1.through indexing
#access 3rd element(means 2 index)from 1Dnumpy array a
a[2]

62

In [17]:
#access multiple elements from 1D numpy array then
#first create a list of index
#suppose access value at 1st and 4th index from 1D array
i=[1,4]#create the list of index
a[i]

array([52, 48])

In [18]:
#2.slicing[start index:stop index:step]
a[1:4]

array([52, 62, 34])

In [19]:
#access element from 3rd index till the end
a[3:]

array([34, 48])

In [20]:
a[-3:-1]

array([62, 34])

In [21]:
a[::-1]#for reverse

array([48, 34, 62, 52, 45])

In [22]:
#to show last 3element
a[-3:]

array([62, 34, 48])

In [23]:
#to access element one by from numpy ARRAY a then use iteration mens
#for loop 
for item in a:
    print(item)

45
52
62
34
48


In [24]:
#to find the sum of element in a
a.sum()

241

In [25]:
#to find average of element in a
a.mean()

48.2

In [26]:
a.max()

62

In [27]:
a.min()

34

In [28]:
#to create a 1D numpy array in another way:use arange()
x=np.arange(10,21,1)
print(x)

[10 11 12 13 14 15 16 17 18 19 20]


In [29]:
#create 2D array menas two dimension numpy array
#2D array means rows and in each row numpycolumns
#each create a matrix
#2Darray means list of list-->[[]]
x=np.array([[10,20,30,40],[50,60,70,80],[20,52,65,85],[45,65,85,96]])
print('matrix x:')
print(x)

matrix x:
[[10 20 30 40]
 [50 60 70 80]
 [20 52 65 85]
 [45 65 85 96]]


In [30]:
#to find out the marks of the student rows
x[2,]

array([20, 52, 65, 85])

In [31]:
#access data from 2Dnumpy array
#1.indexing
#access data from 2nd column of 1st row
x[1,2]#matrix[rowindex,cloindex]

70

In [32]:
#access 1st and 2nd index col of 2nd and 3rd index rows
x[2:4,1:3]#x[row index start:row index stop,col index start,col index stop]

array([[52, 65],
       [65, 85]])

In [33]:
x

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [20, 52, 65, 85],
       [45, 65, 85, 96]])

In [34]:
x[1:3,0:2]

array([[50, 60],
       [20, 52]])

In [35]:
x[:,-1]#find element of last column of all rows

array([40, 80, 85, 96])

In [36]:
#to find out the same of rows
x.sum(axis=1)#axis=1 is use from left to right 

array([100, 260, 222, 291])

In [37]:
#to find the sum of column use axis=0
x.sum(axis=0)#axis=0 use for top to bottom

array([125, 197, 250, 301])

In [38]:
#to find out the max no. from first column
z=x[: ,0]
z.max()

50

In [39]:
x.max()#find out the max no. from whole list

96

In [40]:
#Arithemetic operations on 2D array
#sum of 2 marks
#subtract of 2 matrix
#multiply of 2 matrix

In [41]:
#create a A matrix 2*2
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [42]:
#create a B matrix 2*2
z=np.array([[5,6],[7,8]])
print(z)

[[5 6]
 [7 8]]


In [43]:
x+z

array([[ 6,  8],
       [10, 12]])

In [44]:
x-z

array([[-4, -4],
       [-4, -4]])

In [45]:
#cross multiply
x*z

array([[ 5, 12],
       [21, 32]])

In [46]:
#dot multiply menas row * column for dot()
x.dot(z)

array([[19, 22],
       [43, 50]])

In [47]:
#converts 2D array into 1D array ,numpy provides 3 inbuilt function
#1.ravel() 2.flatten 3.reshape(-1)
#suppose we have 2D array
a=np.array([[10,20,30],[40,50,60],[59,49,60]])
print(a)

[[10 20 30]
 [40 50 60]
 [59 49 60]]


In [48]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [59, 49, 60]])

In [49]:
#convert 2D array into 1D 
a.ravel()

array([10, 20, 30, 40, 50, 60, 59, 49, 60])

In [50]:
a.flatten()

array([10, 20, 30, 40, 50, 60, 59, 49, 60])

In [51]:
a.reshape(-1)

array([10, 20, 30, 40, 50, 60, 59, 49, 60])

In [52]:
# change 1D array into 2D array
#np.reshape(rows,column)
#create a 1D array
a=np.arange(10,20,1)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [53]:
len(a)

10

In [54]:
#change 1D array into 2D array
#a.reshape(2,4)#2 no. of rows and 5 no. of column

In [55]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [56]:
a%2!=0 #odd no. returns false

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [57]:
#access the value of odd no. which return no. and not false
a[a%2!=0]

array([11, 13, 15, 17, 19])

In [58]:
# with use of for loop
for i in a:
    if i%2!=0:
        print(i)# and for horizontal use print(i,end=' ')

11
13
15
17
19


In [59]:
#np.where(condition,True,False)
np.where(a%2!=0,True,False)

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [60]:
b=np.where(a%2!=0,a,'')
print(b)

['' '11' '' '13' '' '15' '' '17' '' '19']


In [61]:
#create a 2D array
a=np.array([[20,40,50],[45,67,89],[60,50,60],[40,50,90]])
b=np.array([[50,60,70],[40,50,60],[54,34,56]])
print('a matrix')
print(a)
print('b matrix')
print(b)

a matrix
[[20 40 50]
 [45 67 89]
 [60 50 60]
 [40 50 90]]
b matrix
[[50 60 70]
 [40 50 60]
 [54 34 56]]


In [62]:
#to join 2 matrix A and B means use concatenate() method of numpy
#array
#concatenate means merge
np.concatenate((a,b),axis=0) #by default axis=0 if did not given

array([[20, 40, 50],
       [45, 67, 89],
       [60, 50, 60],
       [40, 50, 90],
       [50, 60, 70],
       [40, 50, 60],
       [54, 34, 56]])

In [63]:
c=np.array([[50,60,70],[40,50,60],[54,34,56],[90,45,65]])
print(c)

[[50 60 70]
 [40 50 60]
 [54 34 56]
 [90 45 65]]


In [64]:
print(a)

[[20 40 50]
 [45 67 89]
 [60 50 60]
 [40 50 90]]


In [65]:
np.concatenate((a,c),axis=1)

array([[20, 40, 50, 50, 60, 70],
       [45, 67, 89, 40, 50, 60],
       [60, 50, 60, 54, 34, 56],
       [40, 50, 90, 90, 45, 65]])

In [66]:
print(a)

[[20 40 50]
 [45 67 89]
 [60 50 60]
 [40 50 90]]


In [67]:
#create a 2d array
a=np.array([[50,80,70],[40,90,60],[54,34,56],[90,45,65]])
print(a)

[[50 80 70]
 [40 90 60]
 [54 34 56]
 [90 45 65]]


In [68]:
#sort() means to arrange records in ascending order
#by default axis=1 means row wise
a.sort()

In [69]:
print(a)

[[50 70 80]
 [40 60 90]
 [34 54 56]
 [45 65 90]]


In [1]:
a.sort(axis=0)

NameError: name 'a' is not defined

In [71]:
a

array([[34, 54, 56],
       [40, 60, 80],
       [45, 65, 90],
       [50, 70, 90]])

In [72]:
a[::,::-1]#to reverse the column

array([[56, 54, 34],
       [80, 60, 40],
       [90, 65, 45],
       [90, 70, 50]])

In [73]:
#special type of array
#1.zeros() array 2.ones() array 3.empty() array
z=np.zeros(10)
print(z)#returns in float

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [74]:
z=np.zeros(10,int)
print(z) #with the use of int we can remove decimal point

[0 0 0 0 0 0 0 0 0 0]


In [75]:
x=np.empty(10,int)
print(x)

[      0       1       0 7143525    1052       0     768   32763 3801155
 5701724]


In [76]:
y=np.ones(12)
print(y)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [77]:
#create a zeros 1D array
z=np.zeros(8,int)#by default type float
print(z)

[0 0 0 0 0 0 0 0]


In [78]:
#updaat the value at 2nd index with new value 90
z[2]=90
print(z)

[ 0  0 90  0  0  0  0  0]


In [79]:
#create 2D zeros array
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [80]:
#create 2D ones array
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [81]:
#create empty 2D array
a=np.empty((3,3))#byn default type float
print(a)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.19359580e-321]
 [7.44820523e-312 7.44820523e-312 4.94065646e-324]]


In [82]:
#indentity matrixis always 2D
i=np.identity(2)
print(i)

[[1. 0.]
 [0. 1.]]


In [83]:
#eye
i=np.eye(3,dtype=int)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [84]:
a=np.empty(5)
a

array([0., 0., 0., 0., 0.])

In [85]:
a.fill(26)
a

array([26., 26., 26., 26., 26.])

In [86]:
a=np.full(5,26)#we can create this without making empty and fill 
print(a)

[26 26 26 26 26]


In [87]:
#broadcasting
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [88]:
#cretae a vector means 1D array
b=np.array([5,6,7])
print(b)

[5 6 7]


In [89]:
a+b #add the value oF 1D array and vector

array([[15, 26, 37],
       [45, 56, 67],
       [75, 86, 97]])